{% set version = "2.2.6" %}

package:
  name: openalea.sconsx
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - python
    - openalea.deploy #==2.0.0
  run:
    - python
    - scons
    - openalea.deploy

test:
  imports:
    - SCons
    - openalea.sconsx

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
  summary: 'SConsX is an extension package of the SCons build tool. SConsX aims to simplify the build of complex multi-platform packages.'

